In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(1)
b = tf.constant(2)


In [3]:
result= a + b


In [4]:
result

<tf.Tensor 'add:0' shape=() dtype=int32>

In [5]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [6]:
result

3

In [7]:
const = tf.constant(10)

In [21]:
myfill = tf.fill((4,4),10)

In [22]:
myfill

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [23]:
myzeros = tf.zeros((4,4)) 

In [25]:
myones = tf.ones((4,4))

In [26]:
myrandn = tf.random_normal((4,4))

In [27]:
myrandu = tf.random_uniform((4,4),minval=-1,maxval=20)

In [29]:
ops = [const,myfill,myzeros,myones,myrandn,myrandu]

In [30]:
sess = tf.InteractiveSession()

In [35]:
for op in ops:
    print(sess.run(op),end='\n\n')

10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[ 1.7826697   1.4716138  -1.2393215  -1.0474255 ]
 [-1.4020945   0.21711089  0.08208958 -0.8655804 ]
 [-1.1675011   0.8923825  -1.8851548   1.7870362 ]
 [-0.5703124  -0.4622645   0.5069102   2.7909553 ]]

[[ 6.636632   14.900652   18.766289    2.4240713 ]
 [16.360512    1.7163038  10.374594    6.284379  ]
 [11.937977   13.678622    1.3621135   2.7096086 ]
 [ 0.91333234 16.045704   19.960705   16.37268   ]]



In [36]:
a = tf.constant([[1,2],
                 [3,4]])

In [37]:
b = tf.constant([[10],[20]])

In [38]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [39]:
result = tf.matmul(a,b)

In [40]:
sess.run(result)

array([[ 50],
       [110]], dtype=int32)